# Generated by Django 5.0 on 2024-01-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('general', 'GENERAL'), ('special', 'SPECIAL'), ('icu', 'INTENSIVE CARE UNIT'), ('isolation', 'ISOLATION')], max_length=50)),
                ('last_cleaned_date', models.DateField(blank=True, null=True)),
                ('last_cleaned_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_cleaned_date', models.DateField(blank=True, null=True)),
                ('last_cleaned_time', models.TimeField(blank=True, null=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.wardmodel')),
            ],
        ),
    ]
