# Generated by Django 5.0 on 2024-03-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_cleaned_date', models.DateField(blank=True, null=True)),
                ('last_cleaned_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SicknessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('general', 'GENERAL'), ('special', 'SPECIAL'), ('icu', 'INTENSIVE CARE UNIT'), ('isolation', 'ISOLATION')], max_length=50)),
                ('last_cleaned_date', models.DateField(blank=True, null=True)),
                ('last_cleaned_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('price_per_day', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('discharged', 'DISCHARGED')], default='active', max_length=50)),
                ('discharge_note', models.TextField(blank=True, null=True)),
                ('patient_discharge_status', models.CharField(blank=True, choices=[('alive', 'ALIVE'), ('dead', 'DEAD')], default='alive', max_length=20)),
                ('discharge_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_discharge_user', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.bedmodel')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.wardmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('waved_fee', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.admissionmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('discharged', 'DISCHARGED')], default='active', max_length=50)),
                ('discharge_note', models.TextField(blank=True, null=True)),
                ('patient_status', models.CharField(blank=True, choices=[('alive', 'ALIVE'), ('dead', 'DEAD')], default='alive', max_length=20)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.bedmodel')),
                ('discharge_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_user', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.wardmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBabyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('alive', 'ALIVE'), ('dead', 'DEAD')], default='alive', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='medication.deliverymodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('waved_fee', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.deliverymodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bedmodel',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_beds', to='medication.wardmodel'),
        ),
    ]
