# Generated by Django 5.0 on 2024-01-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_alter_conducttestmodel_drug_and_more'),
        ('medication', '0002_sicknessmodel'),
        ('patient', '0004_alter_patientmodel_medication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrugModel',
        ),
    ]
