# Generated by Django 5.0 on 2024-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userprofilemodel_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='default_password',
            field=models.CharField(default='lk', max_length=100),
            preserve_default=False,
        ),
    ]
