# Generated by Django 5.0 on 2024-01-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffidgeneratormodel',
            name='type',
        ),
    ]
