# Generated by Django 5.0 on 2024-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_remove_staffidgeneratormodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='is_doctor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
