# Generated by Django 5.0 on 2024-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_alter_staffmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('access bank', 'ACCESS BANK'), ('uba', 'UNITED BANKS FOR AFRICA')], max_length=100, null=True),
        ),
    ]
