# Generated by Django 5.0 on 2024-02-03 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_daysmodel'),
        ('human_resource', '0008_alter_staffcertificatemodel_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcertificatemodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='human_resource.staffmodel'),
        ),
        migrations.CreateModel(
            name='ShiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.daysmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('maternity leave', 'MATERNITY LEAVE'), ('sick leave', 'SICK LEAVE'), ('others', 'OTHERS')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_count', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('day', 'DAY'), ('week', 'WEEK'), ('month', 'MONTH'), ('year', 'YEAR')], default='week', max_length=30)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('declined', 'DECLINED')], default='pending', max_length=30)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='human_resource.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffShiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts', models.ManyToManyField(blank=True, to='human_resource.shiftmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='human_resource.staffmodel')),
            ],
        ),
    ]
