# Generated by Django 5.0 on 2024-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0009_alter_staffcertificatemodel_staff_shiftmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('access bank', 'ACCESS BANK'), ('first bank', 'FIRST BANK'), ('uba', 'UNITED BANKS FOR AFRICA')], max_length=100, null=True),
        ),
    ]
