# Generated by Django 5.0 on 2024-02-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('mission_one', models.CharField(max_length=500)),
                ('mission_two', models.CharField(max_length=500)),
                ('mission_three', models.CharField(max_length=500)),
                ('mission_four', models.CharField(max_length=500)),
                ('mission_five', models.CharField(max_length=500)),
                ('mission_six', models.CharField(max_length=500)),
                ('mission_seven', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='images/about')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('picture', models.ImageField(upload_to='images/blog')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('opening_hours_monday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('opening_hours_tuesday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('opening_hours_wednesday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('opening_hours_thursday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('opening_hours_friday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('opening_hours_saturday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('opening_hours_sunday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('picture', models.ImageField(upload_to='images/department')),
                ('doctor_image', models.ImageField(upload_to='images/department_doctors')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images/doctor')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('degrees', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeFirstSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(choices=[('homepage', 'HOMEPAGE'), ('about', 'ABOUT')], max_length=30)),
                ('picture', models.ImageField(upload_to='images/slider')),
            ],
        ),
        migrations.CreateModel(
            name='IconBoxAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('Class', models.CharField(default='fa fa-user-md', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHoursModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('tuesday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('wednesday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('thursday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('friday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('saturday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
                ('sunday', models.CharField(blank=True, default='8:00am - 5:00pm', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/services')),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_text', models.TextField()),
                ('site_address', models.CharField(max_length=150)),
                ('site_number', models.CharField(max_length=150)),
                ('site_email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_sickness', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('picture', models.ImageField(upload_to='images/testimonials')),
            ],
        ),
    ]
