# Generated by Django 5.0 on 2024-01-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistrationFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS'), ('others', 'OTHERS')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='patientregistrationfeemodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_patient_reg_fee_name'),
        ),
    ]
