# Generated by Django 5.0 on 2024-03-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(blank=True)),
                ('expense_proof', models.FileField(blank=True, null=True, upload_to='finance/expense')),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_receipt_format', models.CharField(blank=True, choices=[('portrait', 'PORTRAIT'), ('landscape', 'LANDSCAPE')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('declined', 'DECLINED')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(blank=True, null=True)),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='finance/income')),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistrationFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIDGeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField()),
                ('last_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('s', 'SUCCESS'), ('f', 'FAIL')], default='f', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRemittanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('previous_balance', models.FloatField(blank=True, null=True)),
                ('current_balance', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('declined', 'DECLINED')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('amount_forfeited', models.FloatField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='admissionfeemodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_patient_admission_fee_name'),
        ),
        migrations.AddConstraint(
            model_name='deliveryfeemodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_patient_delivery_fee_name'),
        ),
        migrations.AddConstraint(
            model_name='expensecategorymodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_expense_source_combo', violation_error_message='Expense Category Already Exists'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensecategorymodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensetypemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_types', to='finance.expensecategorymodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensetypemodel'),
        ),
        migrations.AddField(
            model_name='fundingmodel',
            name='confirming_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_confirm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.incomecategorymodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='patientregistrationfeemodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_patient_reg_fee_name'),
        ),
        migrations.AddField(
            model_name='paymentremittancemodel',
            name='confirming_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_confirm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentremittancemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='registration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.patientregistrationfeemodel'),
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='incomecategorymodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_income_category_combo', violation_error_message='Income Category Already Exists'),
        ),
    ]
