# Generated by Django 5.0 on 2024-01-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_registrationpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
