# Generated by Django 5.0 on 2024-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_registrationpaymentmodel_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationpaymentmodel',
            old_name='payment_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED')], default='ll', max_length=50),
            preserve_default=False,
        ),
    ]
