# Generated by Django 5.0 on 2024-01-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_payment_id_registrationpaymentmodel_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_receipt_format', models.CharField(blank=True, choices=[('portrait', 'PORTRAIT'), ('landscape', 'LANDSCAPE')], max_length=50, null=True)),
            ],
        ),
    ]
