# Generated by Django 5.0 on 2024-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financesettingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistrationfeemodel',
            name='insurance',
            field=models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True),
        ),
    ]
