# Generated by Django 5.0 on 2024-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_patientregistrationfeemodel_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='amount_forfeited',
            field=models.FloatField(default=0),
        ),
    ]
