# Generated by Django 5.0 on 2024-02-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_registrationpaymentmodel_amount_forfeited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationpaymentmodel',
            name='created_at',
        ),
    ]
