# Generated by Django 5.0 on 2024-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_registrationpaymentmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpaymentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-05-05'),
            preserve_default=False,
        ),
    ]
