# Generated by Django 5.0 on 2024-02-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_registrationpaymentmodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationpaymentmodel',
            options={'ordering': ['id']},
        ),
    ]
