# Generated by Django 5.0 on 2024-02-26 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_incomemodel_source_delete_incomesourcemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incomemodel',
            name='unique_income_invoice_combo',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='incomemodel',
            name='invoice_number',
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
