# Generated by Django 5.0 on 2024-01-27 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0003_delete_drugmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normal_lower_limit', models.FloatField(blank=True, null=True)),
                ('normal_upper_limit', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fields', models.ManyToManyField(blank=True, to='laboratory.testfieldmodel')),
                ('possible_sicknesses', models.ManyToManyField(blank=True, to='medication.sicknessmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='testunitmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_test_unit_name_combo'),
        ),
        migrations.AddField(
            model_name='testfieldmodel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.testunitmodel'),
        ),
        migrations.AddConstraint(
            model_name='testmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_test_name_combo'),
        ),
        migrations.AddConstraint(
            model_name='testfieldmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_test_field_name_combo'),
        ),
    ]
