# Generated by Django 5.0 on 2024-01-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS'), ('others', 'OTHERS')], max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.testmodel')),
            ],
        ),
    ]
