# Generated by Django 5.0 on 2024-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_testpricemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testunitmodel',
            name='order',
        ),
        migrations.AddField(
            model_name='testfieldmodel',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
