# Generated by Django 5.0 on 2024-01-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_testfieldmodel_result_type_testfieldmodel_test_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfieldmodel',
            old_name='test_code',
            new_name='field_code',
        ),
    ]
