# Generated by Django 5.0 on 2024-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_rename_test_code_testfieldmodel_field_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='test_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
