# Generated by Django 5.0 on 2024-01-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_testmodel_test_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='test_code',
            new_name='code',
        ),
    ]
