# Generated by Django 5.0 on 2024-01-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_rename_test_code_testmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpricemodel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='laboratory.testmodel'),
        ),
    ]
