# Generated by Django 5.0 on 2024-02-17 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_alter_testpricemodel_insurance'),
        ('patient', '0009_patientprofilemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('payment_made', models.BooleanField(blank=True, default=False)),
                ('sample_collected', models.BooleanField(blank=True, default=False)),
                ('conducted', models.CharField(blank=True, choices=[('internal', 'INTERNAL'), ('external', 'EXTERNAL')], max_length=20, null=True)),
                ('result_ready', models.BooleanField(blank=True, default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.testmodel')),
            ],
        ),
    ]
