# Generated by Django 5.0 on 2024-02-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_conducttestresultmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20),
        ),
    ]
