# Generated by Django 5.0 on 2024-02-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_testmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducttestresultmodel',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratory.conducttestmodel'),
        ),
    ]
