# Generated by Django 5.0 on 2024-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_alter_conducttestresultmodel_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducttestmodel',
            name='sample_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
