# Generated by Django 5.0 on 2024-02-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_conducttestmodel_sample_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducttestresultmodel',
            name='type',
            field=models.CharField(blank=True, default='test_result', max_length=20),
        ),
    ]
