# Generated by Django 5.0 on 2024-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_conducttestresultmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducttestresultmodel',
            name='doctor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conducttestresultmodel',
            name='lab_attendant_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
