# Generated by Django 5.0 on 2024-02-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0016_conducttestresultmodel_doctor_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducttestresultmodel',
            name='doctor_comment',
        ),
    ]
