# Generated by Django 5.0 on 2024-03-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DrugStrengthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DrugUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DrugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, to='pharmacy.drugcategorymodel')),
                ('sickness', models.ManyToManyField(blank=True, to='medication.sicknessmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DrugStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.FloatField()),
                ('quantity_left', models.FloatField(blank=True, default=0)),
                ('total_cost_price', models.FloatField(blank=True, null=True)),
                ('unit_cost_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('current_worth', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugbatchmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrugStockOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('worth', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugstockmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DrugVariantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, choices=[('capsule', 'CAPSULE'), ('injection', 'INJECTION'), ('syrup', 'SYRUP'), ('balm', 'BALM')], default='capsule', max_length=50, null=True)),
                ('quantity', models.FloatField(blank=True, default=0)),
                ('low_limit', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_variants', to='pharmacy.drugmodel')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugmanufacturermodel')),
                ('strength', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugstrengthmodel')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugunitmodel')),
            ],
        ),
        migrations.AddField(
            model_name='drugstockmodel',
            name='drug_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugvariantmodel'),
        ),
        migrations.CreateModel(
            name='DrugVariantPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('drug_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_prices', to='pharmacy.drugvariantmodel')),
            ],
        ),
    ]
