# Generated by Django 5.0 on 2024-01-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_drugcategorymodel_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='drugmodel',
            name='manufacturer',
        ),
    ]
