# Generated by Django 5.0 on 2024-01-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_drugmanufacturermodel_remove_drugmodel_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugStrengthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='drugmodel',
            name='quantity_available',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='DrugStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugbatchmodel')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugunitmodel')),
                ('strength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugstrengthmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DrugAvailabilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugunitmodel')),
                ('strength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugstrengthmodel')),
            ],
        ),
    ]
