# Generated by Django 5.0 on 2024-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_drugbatchmodel_drugstrengthmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmodel',
            name='selling_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
