# Generated by Django 5.0 on 2024-01-27 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_drugmodel_selling_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugstockmodel',
            old_name='cost_price',
            new_name='quantity_bought',
        ),
        migrations.RenameField(
            model_name='drugstockmodel',
            old_name='quantity',
            new_name='total_cost_price',
        ),
        migrations.AddField(
            model_name='drugstockmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='drugstockmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugstockmodel',
            name='quantity_left',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='drugstockmodel',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='drugstockmodel',
            name='unit_cost_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DrugStockOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('worth', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugstockmodel')),
            ],
        ),
    ]
