# Generated by Django 5.0 on 2024-02-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_rename_cost_price_drugstockmodel_quantity_bought_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pharmacy.drugmodel')),
            ],
        ),
    ]
