# Generated by Django 5.0 on 2024-02-27 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_remove_drugpricemodel_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugvariantmodel',
            name='form',
            field=models.CharField(blank=True, choices=[('capsule', 'CAPSULE'), ('injection', 'INJECTION'), ('syrup', 'SYRUP'), ('balm', 'BALM')], default='capsule', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drugvariantmodel',
            name='strength',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugstrengthmodel'),
        ),
        migrations.AlterField(
            model_name='drugvariantmodel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugunitmodel'),
        ),
    ]
