# Generated by Django 5.0 on 2024-02-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_drugvariantmodel_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugvariantmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_variants', to='pharmacy.drugmanufacturermodel'),
        ),
    ]
