# Generated by Django 5.0 on 2024-02-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_alter_drugvariantmodel_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugvariantmodel',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_variants', to='pharmacy.drugmodel'),
        ),
        migrations.AlterField(
            model_name='drugvariantmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugmanufacturermodel'),
        ),
    ]
