# Generated by Django 5.0 on 2024-02-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_drugvariantmodel_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbatchmodel',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
