# Generated by Django 5.0 on 2024-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_drugbatchmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbatchmodel',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
