# Generated by Django 5.0 on 2024-02-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_alter_drugbatchmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbatchmodel',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
