# Generated by Django 5.0 on 2024-02-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_alter_drugbatchmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstockmodel',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugbatchmodel'),
        ),
        migrations.AlterField(
            model_name='drugstockmodel',
            name='total_cost_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
