# Generated by Django 5.0 on 2024-01-27 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorysuppliermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugstockoutmodel',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='drugstockoutmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='drugstockoutmodel',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='stockoutmodel',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stockoutmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockoutmodel',
            name='inventory',
        ),
        migrations.CreateModel(
            name='InventoryStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.FloatField()),
                ('quantity_left', models.FloatField(blank=True, default=0)),
                ('total_cost_price', models.FloatField()),
                ('unit_cost_price', models.FloatField()),
                ('status', models.CharField(blank=True, default='active', max_length=15)),
                ('batch', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStockOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('worth', models.FloatField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorystockmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='DrugStockInModel',
        ),
        migrations.DeleteModel(
            name='DrugStockOutModel',
        ),
        migrations.DeleteModel(
            name='StockInModel',
        ),
        migrations.DeleteModel(
            name='StockOutModel',
        ),
    ]
