# Generated by Django 5.0 on 2024-02-21 12:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_drugstockoutmodel_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorystockoutmodel',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventorystockmodel',
            name='inventory',
        ),
        migrations.RenameField(
            model_name='inventorystockmodel',
            old_name='quantity_bought',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='inventorystockmodel',
            old_name='total_cost_price',
            new_name='unit_cost',
        ),
        migrations.RenameField(
            model_name='inventorystockmodel',
            old_name='unit_cost_price',
            new_name='unit_selling',
        ),
        migrations.RenameField(
            model_name='inventorystockoutmodel',
            old_name='remark',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='unique_tag',
        ),
        migrations.RemoveField(
            model_name='inventorystockmodel',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='inventorystockmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorystockmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inventorystockoutmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorystockoutmodel',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='inventorystockoutmodel',
            name='worth',
        ),
        migrations.RemoveField(
            model_name='inventorysuppliermodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assetcategorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategorymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='asset_type',
            field=models.CharField(choices=[('fixed', 'FIXED'), ('movable', 'MOVABLE')], default='dd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='worth',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorycategorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorycategorymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorycategorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystockmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorysuppliermodel'),
        ),
        migrations.AddField(
            model_name='inventorystockmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorystockmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stock_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystockmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystockoutmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2024, 2, 21)),
        ),
        migrations.AddField(
            model_name='inventorystockoutmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorysuppliermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetcategorymodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.assetcategorymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inventorycategorymodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inventorystockmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2024, 2, 21)),
        ),
        migrations.AlterField(
            model_name='inventorystockmodel',
            name='quantity_left',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventorysuppliermodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default=('active', 'ACTIVE'), max_length=10),
        ),
        migrations.CreateModel(
            name='InventoryItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('selling_price', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorycategorymodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventorystockmodel',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_list', to='inventory.inventoryitemmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorystockoutmodel',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitemmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventoryStockOutSummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.date(2024, 2, 21))),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('items', models.ManyToManyField(related_name='stock_out_summary', to='inventory.inventorystockoutmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryModel',
        ),
    ]
