# Generated by Django 5.0 on 2024-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventorystockoutmodel_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystockoutmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
