# Generated by Django 5.0 on 2024-02-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorystockoutmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemmodel',
            name='low_limit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
