# Generated by Django 5.0 on 2024-02-27 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_assetmodel_asset_type_alter_assetmodel_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorystockmodel',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.DeleteModel(
            name='InventoryStockOutSummaryModel',
        ),
    ]
