# Generated by Django 5.0 on 2024-02-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorystockoutmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystockoutmodel',
            name='worth',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
