# Generated by Django 5.0 on 2024-02-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('human_resource', '0010_alter_staffmodel_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitorrecordmodel',
            name='staff_to_see',
        ),
        migrations.RemoveField(
            model_name='communicationsettingmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='smsconfigurationmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='smsconfigurationmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='smsconfigurationmodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='smtpconfigurationmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='smtpconfigurationmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='smtpconfigurationmodel',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='smsmodel',
            name='staff',
            field=models.ManyToManyField(blank=True, to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='smsconfigurationmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default=('active', 'ACTIVE'), max_length=20),
        ),
        migrations.AlterField(
            model_name='smsmodel',
            name='receiver',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='smtpconfigurationmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default=('active', 'ACTIVE'), max_length=20),
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('receiver', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_sender', to='human_resource.staffmodel')),
                ('staff', models.ManyToManyField(blank=True, to='human_resource.staffmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='SentMessageModel',
        ),
        migrations.DeleteModel(
            name='VisitorRecordModel',
        ),
    ]
