# Generated by Django 5.0 on 2024-02-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_contactmodel_remove_visitorrecordmodel_staff_to_see_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontDeskInfoModel',
        ),
        migrations.RemoveField(
            model_name='communicationsettingmodel',
            name='default_sms',
        ),
        migrations.RemoveField(
            model_name='smsmodel',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='smsmodel',
            name='staff',
        ),
        migrations.DeleteModel(
            name='SMSConfigurationModel',
        ),
        migrations.DeleteModel(
            name='SMSModel',
        ),
    ]
