# Generated by Django 5.0 on 2024-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_last_student_id_patientidgeneratormodel_last_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitalsmodel',
            name='extra_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
