# Generated by Django 5.0 on 2024-01-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientvitalsmodel_extra_note'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='medication',
            field=models.ManyToManyField(blank=True, to='pharmacy.drugmodel'),
        ),
    ]
