# Generated by Django 5.0 on 2024-02-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_registrationpaymentmodel_created_at'),
        ('patient', '0005_alter_patientmodel_insurance_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='registration_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.registrationpaymentmodel'),
        ),
    ]
