# Generated by Django 5.0 on 2024-02-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientmodel_registration_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='registration_payment',
        ),
    ]
