# Generated by Django 5.0 on 2024-02-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patientprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='number_of_visits',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
