# Generated by Django 5.0 on 2024-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patientmodel_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitalsmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
