# Generated by Django 5.0 on 2024-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_in_maintenance', models.BooleanField(default=False)),
                ('auto_user_account', models.BooleanField(default=False)),
                ('patient_registration_without_payment', models.BooleanField(default=False)),
                ('allow_user_login', models.BooleanField(default=False)),
                ('auto_generate_staff_id', models.BooleanField(default=True)),
                ('auto_generate_card_number', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalCertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('document', models.FileField(upload_to='images/certificate')),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(blank=True, default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=50)),
                ('mobile_1', models.CharField(max_length=20)),
                ('mobile_2', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(upload_to='images/setting/logo')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='images/setting/logo')),
                ('preloader', models.FileField(blank=True, null=True, upload_to='images/setting/logo')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_handle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
