# Generated by Django 5.0 on 2024-01-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfomodel',
            name='github_handle',
        ),
    ]
