# Generated by Django 5.0 on 2024-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_remove_siteinfomodel_github_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
