# Generated by Django 5.0 on 2024-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_daysmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettingmodel',
            name='staff_registration_without_payment',
            field=models.BooleanField(default=False),
        ),
    ]
