# Generated by Django 5.0 on 2024-02-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_generalsettingmodel_staff_registration_without_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettingmodel',
            old_name='staff_registration_without_payment',
            new_name='patient_registration_without_payment',
        ),
    ]
