# Generated by Django 5.0 on 2024-01-18 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource', '0005_alter_staffmodel_bank_name'),
        ('medication', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('duration', models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('annually', 'ANNUALLY')], default='daily', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS'), ('others', 'OTHERS')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('amount_paid', models.FloatField()),
                ('balance_credited', models.FloatField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationPrescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
                ('prescription', models.ManyToManyField(to='medication.drugmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationQueueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('amount_paid', models.FloatField()),
                ('balance_credited', models.FloatField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('awaiting', 'AWAITING'), ('progress', 'PROGRESS'), ('paused', 'PAUSED'), ('complete', 'COMPLETE')], max_length=50)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultationblockmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationSeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.consultationblockmodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultationroommodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
                ('test', models.ManyToManyField(to='medication.drugmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsultationQueueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('amount_paid', models.FloatField()),
                ('balance_credited', models.FloatField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('awaiting', 'AWAITING'), ('progress', 'PROGRESS'), ('paused', 'PAUSED'), ('complete', 'COMPLETE')], max_length=50)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.drugmodel')),
            ],
        ),
    ]
