# Generated by Django 5.0 on 2024-03-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBlockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationFeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('duration', models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('annually', 'ANNUALLY')], default='daily', max_length=100)),
                ('insurance', models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('amount_paid', models.FloatField()),
                ('balance_credited', models.FloatField(blank=True, default=0)),
                ('amount_forfeited', models.FloatField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_posted', models.BooleanField(blank=True, default=False)),
                ('is_attended', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(blank=True, choices=[('not posted', 'NOT POSTED'), ('posted', 'posted'), ('progress', 'PROGRESS'), ('complete', 'COMPLETE')], default='not posted', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationPrescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.FloatField(blank=True, default=0)),
                ('amount_paid', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(blank=True, default='prescription', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('grand_total', models.FloatField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, default=0)),
                ('payment_status', models.CharField(choices=[('not paid', 'NOT PAID'), ('paid', 'PAID')], default=('not paid', 'NOT PAID'), max_length=50)),
                ('type', models.CharField(blank=True, default='test', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsultationQueueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30)),
                ('posting_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField()),
                ('unit_selling_price', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('drug_available', models.BooleanField(blank=True, default=False)),
                ('payment_made', models.BooleanField(blank=True, default=False)),
                ('collected', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('follow up', 'FOLLOW UP'), ('conclusion', 'CONCLUSION'), ('admission', 'ADMISSION')], default='new', max_length=30)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, default='consultation', max_length=30)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.admissionmodel')),
            ],
        ),
    ]
