# Generated by Django 5.0 on 2024-01-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationSeatModel',
        ),
    ]
