# Generated by Django 5.0 on 2024-03-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('human_resource', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('medication', '0001_initial'),
        ('patient', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='attendant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_doctor', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cons_payment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationprescriptionmodel',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.admissionmodel'),
        ),
        migrations.AddField(
            model_name='consultationprescriptionmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationprescriptionmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='consultationroommodel',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultationblockmodel'),
        ),
        migrations.AddField(
            model_name='consultationtestmodel',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.admissionmodel'),
        ),
        migrations.AddField(
            model_name='consultationtestmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationtestmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='consultationtestmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='laboratory.conducttestmodel'),
        ),
        migrations.AddField(
            model_name='doctorconsultationqueuemodel',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultationblockmodel'),
        ),
        migrations.AddField(
            model_name='doctorconsultationqueuemodel',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_queue', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='doctorconsultationqueuemodel',
            name='patients',
            field=models.ManyToManyField(blank=True, to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='doctorconsultationqueuemodel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.consultationroommodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.admissionmodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='collection_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pres_collect_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugvariantmodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_patient', to='patient.patientmodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='payment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pres_payment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationprescriptionmodel',
            name='prescriptions',
            field=models.ManyToManyField(to='consultation.prescriptionmodel'),
        ),
    ]
