# Generated by Django 5.0 on 2024-01-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_delete_consultationseatmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationfeemodel',
            name='description',
        ),
    ]
