# Generated by Django 5.0 on 2024-01-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_remove_consultationfeemodel_description'),
        ('human_resource', '0005_alter_staffmodel_bank_name'),
        ('patient', '0002_rename_last_student_id_patientidgeneratormodel_last_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorconsultationqueuemodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='doctorconsultationqueuemodel',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='doctorconsultationqueuemodel',
            name='attendant',
        ),
        migrations.RemoveField(
            model_name='doctorconsultationqueuemodel',
            name='balance_credited',
        ),
        migrations.RemoveField(
            model_name='doctorconsultationqueuemodel',
            name='status',
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='is_attended',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='is_posted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RemoveField(
            model_name='doctorconsultationqueuemodel',
            name='patient',
        ),
        migrations.DeleteModel(
            name='ConsultationQueueModel',
        ),
        migrations.AddField(
            model_name='doctorconsultationqueuemodel',
            name='patient',
            field=models.ManyToManyField(blank=True, to='patient.patientmodel'),
        ),
    ]
