# Generated by Django 5.0 on 2024-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultationpaymentmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorconsultationqueuemodel',
            old_name='patient',
            new_name='patients',
        ),
        migrations.RemoveField(
            model_name='doctorconsultationqueuemodel',
            name='date',
        ),
        migrations.AddField(
            model_name='doctorconsultationqueuemodel',
            name='doctor_status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='ll', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorconsultationqueuemodel',
            name='posting_status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='ll', max_length=30),
            preserve_default=False,
        ),
    ]
