# Generated by Django 5.0 on 2024-01-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_rename_patient_doctorconsultationqueuemodel_patients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationmodel',
            old_name='consultation',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('follow up', 'FOLLOW UP'), ('conclusion', 'CONCLUSION')], default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='consultationmodel',
            name='subject',
            field=models.CharField(default='gg', max_length=250),
            preserve_default=False,
        ),
    ]
