# Generated by Django 5.0 on 2024-01-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_consultationprescriptionmodel_amount_paid_and_more'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducttestmodel',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel'),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drugmodel'),
        ),
    ]
