# Generated by Django 5.0 on 2024-01-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_alter_conducttestmodel_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='pres_id',
            field=models.IntegerField(blank=True),
        ),
    ]
