# Generated by Django 5.0 on 2024-01-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_alter_prescriptionmodel_pres_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationprescriptionmodel',
            old_name='sale_id',
            new_name='pres_id',
        ),
    ]
