# Generated by Django 5.0 on 2024-01-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_rename_sale_id_consultationprescriptionmodel_pres_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='unit_cost_price',
        ),
    ]
