# Generated by Django 5.0 on 2024-01-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_remove_prescriptionmodel_unit_cost_price'),
        ('pharmacy', '0005_drugmodel_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmodel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugunitmodel'),
        ),
        migrations.AlterField(
            model_name='consultationprescriptionmodel',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='consultationprescriptionmodel',
            name='grand_total',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='strength',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugstrengthmodel'),
        ),
    ]
