# Generated by Django 5.0 on 2024-01-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0014_remove_conducttestmodel_created_by_and_more'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationtestmodel',
            name='test',
            field=models.ManyToManyField(to='laboratory.testmodel'),
        ),
        migrations.DeleteModel(
            name='ConductTestModel',
        ),
    ]
