# Generated by Django 5.0 on 2024-01-27 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0015_alter_consultationtestmodel_test_and_more'),
        ('laboratory', '0002_testpricemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationtestmodel',
            name='test',
        ),
        migrations.AddField(
            model_name='consultationtestmodel',
            name='payment_status',
            field=models.CharField(default='not paid', max_length=50),
        ),
        migrations.CreateModel(
            name='ConductTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('payment_status', models.CharField(default='not paid', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.testmodel')),
            ],
        ),
        migrations.AddField(
            model_name='consultationtestmodel',
            name='tests',
            field=models.ManyToManyField(to='consultation.conducttestmodel'),
        ),
    ]
