# Generated by Django 5.0 on 2024-01-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0016_remove_consultationtestmodel_test_and_more'),
        ('patient', '0004_alter_patientmodel_medication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducttestmodel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='conducttestmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conducttestmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmodel'),
        ),
        migrations.AlterField(
            model_name='consultationtestmodel',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='consultationtestmodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultationtestmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='consultation.conducttestmodel'),
        ),
    ]
