# Generated by Django 5.0 on 2024-02-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0017_remove_conducttestmodel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconsultationqueuemodel',
            name='doctor_status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorconsultationqueuemodel',
            name='posting_status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=30),
        ),
    ]
