# Generated by Django 5.0 on 2024-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_alter_doctorconsultationqueuemodel_doctor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationfeemodel',
            name='insurance',
            field=models.CharField(blank=True, choices=[('nhis', 'NHIS')], max_length=100, null=True),
        ),
    ]
