# Generated by Django 5.0 on 2024-02-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0019_alter_consultationfeemodel_insurance'),
        ('human_resource', '0010_alter_staffmodel_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconsultationqueuemodel',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='human_resource.staffmodel'),
            preserve_default=False,
        ),
    ]
