# Generated by Django 5.0 on 2024-02-04 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0020_alter_doctorconsultationqueuemodel_doctor'),
        ('human_resource', '0010_alter_staffmodel_bank_name'),
        ('patient', '0009_patientprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='attended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel'),
        ),
    ]
