# Generated by Django 5.0 on 2024-02-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0021_alter_consultationpaymentmodel_attended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='amount_forfeited',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
