# Generated by Django 5.0 on 2024-02-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0022_consultationpaymentmodel_amount_forfeited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationpaymentmodel',
            name='attended_by',
        ),
    ]
