# Generated by Django 5.0 on 2024-02-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0023_remove_consultationpaymentmodel_attended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-07-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationpaymentmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
