# Generated by Django 5.0 on 2024-02-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0024_consultationpaymentmodel_created_at_and_more'),
        ('patient', '0009_patientprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmodel',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.patientmodel'),
            preserve_default=False,
        ),
    ]
