# Generated by Django 5.0 on 2024-02-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0025_alter_consultationmodel_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationmodel',
            old_name='date',
            new_name='created_at',
        ),
    ]
