# Generated by Django 5.0 on 2024-02-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0026_rename_date_consultationmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmodel',
            name='type',
            field=models.CharField(blank=True, default='consultation', max_length=30),
        ),
    ]
