# Generated by Django 5.0 on 2024-02-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0027_consultationmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
