# Generated by Django 5.0 on 2024-02-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0028_remove_prescriptionmodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationprescriptionmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='consultationprescriptionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='collection_status',
            field=models.CharField(choices=[('not collected', 'NOT COLLECTED'), ('collected', 'COLLECTED')], default=('not collected', 'NOT COLLECTED'), max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='payment_status',
            field=models.CharField(choices=[('not paid', 'NOT PAID'), ('paid', 'PAID')], default=('not paid', 'NOT PAID'), max_length=20),
        ),
    ]
