# Generated by Django 5.0 on 2024-02-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0029_remove_consultationprescriptionmodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationprescriptionmodel',
            name='type',
            field=models.CharField(blank=True, default='prescription', max_length=30),
        ),
    ]
