# Generated by Django 5.0 on 2024-02-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0031_conducttestmodel_result_ready_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationtestmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='consultationtestmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
