# Generated by Django 5.0 on 2024-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0032_remove_consultationtestmodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducttestmodel',
            name='conducted',
            field=models.CharField(blank=True, choices=[('internal', 'INTERNAL'), ('external', 'EXTERNAL')], max_length=20, null=True),
        ),
    ]
