# Generated by Django 5.0 on 2024-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0033_conducttestmodel_conducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducttestmodel',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='conducttestmodel',
            name='payment_made',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
