# Generated by Django 5.0 on 2024-02-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0034_remove_conducttestmodel_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducttestmodel',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='conducttestmodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='conducttestmodel',
            name='test',
        ),
    ]
