# Generated by Django 5.0 on 2024-02-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0035_remove_conducttestmodel_doctor_and_more'),
        ('laboratory', '0010_conducttestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationtestmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='laboratory.conducttestmodel'),
        ),
        migrations.DeleteModel(
            name='ConductTestModel',
        ),
    ]
