# Generated by Django 5.0 on 2024-02-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0036_alter_consultationtestmodel_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationtestmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
