# Generated by Django 5.0 on 2024-02-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0037_consultationtestmodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationprescriptionmodel',
            old_name='prescription',
            new_name='prescriptions',
        ),
    ]
