# Generated by Django 5.0 on 2024-02-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0038_rename_prescription_consultationprescriptionmodel_prescriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
