# Generated by Django 5.0 on 2024-02-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0039_alter_prescriptionmodel_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationprescriptionmodel',
            name='pres_id',
        ),
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='pres_id',
        ),
    ]
