# Generated by Django 5.0 on 2024-02-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0040_remove_consultationprescriptionmodel_pres_id_and_more'),
        ('human_resource', '0010_alter_staffmodel_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconsultationqueuemodel',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_queue', to='human_resource.staffmodel'),
        ),
    ]
