# Generated by Django 5.0 on 2024-02-24 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0041_alter_doctorconsultationqueuemodel_doctor'),
        ('human_resource', '0010_alter_staffmodel_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaymentmodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_doctor', to='human_resource.staffmodel'),
        ),
    ]
