# Generated by Django 5.0 on 2024-02-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource', '0010_alter_staffmodel_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.staffmodel')),
            ],
        ),
    ]
