# Generated by Django 5.0 on 2024-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.JSONField(blank=True, null=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
